### PR TITLE
Add initial Gradle plugin

### LINKED ISSUE #44: Investigate adding support for Gradle

### PR DESCRIPTION
**Pull request by wandernauta**
The Gradle plugin follows the behavior of the Maven plugin: if it is applied, it automatically generates a `livingdocumentation.json` file for the Java source that's in the project every time the project is compiled. In addition, the task can be run manually with `./gradlew generateLivingDocumentation` (or `./gradlew gLD` for short), or through IDE integration. Since Gradle tracks input and output files, this is a no-op if no files have changed since the last time the JSON was generated.

Since the plugin is (of course) not yet published, it needs to be built and added to the build script classpath manually. To try it out in a new Gradle project, add this to the top, changing the path to match:

```groovy
buildscript {
    repositories {
        flatDir { dir '/path/to/ISEP-LivingDocumentation/ldj-gradle-plugin/target' }
    }
    dependencies {
        classpath 'com.infosupport.livingdocumentation:ldj-gradle-plugin:1-SNAPSHOT'
    }
}
```

Then, add to the bottom:

```groovy
apply plugin: 'com.infosupport.ldoc'
```

The plugin assumes that the 'java' plugin is also applied to the project.

Closes #44.

### CODE REVIEW

**Comment by GuusVink** [comment]
Looked over the code and read into some Gradle documentation as I am not at all familiar with Gradle. So I don't know whether I am the best person to do this review, but I suspect that holds for any person in our group :)

Some general questions/comments:

1. I verified that the Gradle plugin works as you described. However, shouldn't we also include a plugin-example project? (similar to the maven-plugin-example)?

2. How do we plan to publish this plugin in the future? From what I can find online, if we want to publish to the Gradle plugin portal, the plugin project should be a Gradle project (as opposed to Maven which it currently is). If we would transform this module to a Gradle project, it would not fit nicely into the 'parent' hierarchy (and may complicate adding a dependency to the analyzer module). However, it may be worth this 'cost' if it allows to more nicely publish the plugin.
(some discussion regarding this topic https://discuss.gradle.org/t/how-to-publish-mirror-a-plugin-available-from-maven-central-to-the-gradle-plugin-portal/41526)

I must admit I am not in a state where I can say whether both approaches are even possible. But it might be good to think about this as I do not see a plugin that can only be installed locally to be a useful addition to this repository. _(I know the maven plugin currently can also only be installed locally, but I am a bit more optimistic that that one can be published without too much hassle)_

**Comment by wandernauta** [comment]
Thanks for taking a look!

> Should we also include a plugin-example project?

We could, but it would be less useful than the Maven plugin example. I added the Maven plugin example so that our GitHub Actions build runs the Maven plugin at least once. People can copy-paste from the plugin example's `pom.xml` into their own project if they want to, but that is basically a side benefit. The main benefit would not apply here because we don't build with Gradle, we only build a plugin for it.

With that in mind, I've instead added a README file that contains more or less the instructions above. Would that be sufficient?

> ...if we want to publish to the Gradle plugin portal...

I don't think we need to do this, or definitely not yet. The Gradle plugin portal seems to be like an App Store kind of thing where you can advertise your plugin to Gradle enthousiasts after going through a manual approval process - it sounds like more than we need right now.

I'm envisioning that once we are ready to publish everything (and know what the thing is going to be called!), we publish everything to Maven Central and (update the new README to) tell people to grab the plugin from there. That basically amounts to adding this to `settings.gradle`:

```
pluginManagement {
    repositories {
        mavenCentral()
    }
}
```

and this to `build.gradle`:

```
plugins {
    id 'java'
    id 'com.infosupport.ldoc' version '1.0'
}
```

and we don't have to interact with the Gradle plugin portal at all.

I would not be in favor of somehow using different build systems for different bits of the project.

**Comment by GuusVink** [comment]
The added ReadME seems sufficient to me.

As for the publishing; we now made the decision to publish the plugin to maven central at a later point (and we are ok with not being able to link to the Gradle portal). As this seems reasonable to me, we can merge this PR

**Review by GuusVink — APPROVED** [review]
See previous comment for reason approval

**Pull request merged**
